- name: Ensure vim is not installed in parallel to neoVim.
  ansible.builtin.homebrew:
    name: "{{ item }}"
    state: absent
  with_items:
    - vim

# we need to install `findutils` since the macOS default version is just broken and old
- name: Ensure neoVim and some additional tools are installed on the computer.
  ansible.builtin.homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - ctags
    - fzf
    - git
    - nvim
    - uutils-findutils
